version: 0.2
os: linux
files:
  - source: /frontend/*
    destination: /home/ec2-user/frontend/
  - source: /backend/*
    destination: /home/ec2-user/backend/

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_containers.sh
      timeout: 180
      runas: ec2-user