version: 0.0
os: linux
files:
  - source: /  # All files are copied over
    destination: /home/ubuntu/snaptweet  # Destination folder on EC2

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh  # Script to install dependencies, e.g., Docker
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/stop_docker_containers.sh  # Stop existing containers if any
      timeout: 300
      runas: ubuntu
    - location: scripts/start_docker_containers.sh  # Start the new containers
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/monitor_docker_containers.sh  # Ensure containers are running
      timeout: 300
      runas: ubuntu
